In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [5]:

df = pd.read_csv(r'C:\Users\SHUBHAM\Downloads\Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
df.head(4)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0

In [7]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [8]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [10]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
X

array([[1.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 1.0, ..., 1, 0, 38190.78]],
      shape=(10000, 13), dtype=object)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [16]:
X

array([[ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 0.57873591, -0.57873591, -1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.57873591, -0.57873591,  0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.72790383,  1.72790383, -1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.57873591, -0.57873591,  0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 13))

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20, random_state=0)

In [18]:
print(X_train.shape)

(8000, 13)

In [19]:
print(X_test.shape)

(2000, 13)

In [20]:
print(y_train.shape)

(8000,)

In [21]:
print(y_test.shape)

(2000,)

In [22]:
# ANN ARTICATURE

In [23]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 5,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 4,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

In [24]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [25]:
ann.fit(X_train,y_train , batch_size=32,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.7960 - loss: 0.5237
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7960 - loss: 0.4712
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7960 - loss: 0.4470
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7960 - loss: 0.4349
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8027 - loss: 0.4290
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8164 - loss: 0.4248
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8207 - loss: 0.4221
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8240 - loss: 0.4188
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8240 - loss: 0.4156
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8281 - loss: 0.4127

In [26]:
y_pred = ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

In [27]:
y_pred

array([[0.18986349],
       [0.36706272],
       [0.11821439],
       ...,
       [0.19290195],
       [0.14321126],
       [0.17858881]], shape=(2000, 1), dtype=float32)

In [28]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis = 1))

[[0.18986349 0.        ]
 [0.36706272 1.        ]
 [0.11821439 0.        ]
 ...
 [0.19290195 0.        ]
 [0.14321126 0.        ]
 [0.17858881 0.        ]]

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Convert probabilities into binary predictions
y_pred_class = (y_pred > 0.5).astype(int)

# Calculate accuracy
ac = accuracy_score(y_test, y_pred_class)

print("Accuracy:", ac)

Accuracy: 0.8385

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix

ac = accuracy_score(y_test,y_pred)
ac

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [32]:
cm = confusion_matrix(y_test,y_pred)
cm

ValueError: Classification metrics can't handle a mix of binary and continuous targets